### ISSUE TITLE
Invalid page and filter params aren't validated

### ISSUE THREAD

**Issue by LavaToaster** [neomerx/json-api#58]
If you decide to add in a non-spec parameter to the request such as `page=2`, the application errors out. This should be handled and result in a 400 Bad Request instead.

The affected parameters I'm aware of are:
- `page`
- `filter`

This is the from the error log:

```
[2015-08-05 13:50:57] local.ERROR: exception 'ErrorException' with message 'Argument 6 passed to Neomerx\JsonApi\Factories\Factory::createParameters() must be of the type array, string given, called in /home/vagrant/www/work/lyf/vendor/neomerx/json-api/src/Parameters/ParametersParser.php on line 100 and defined' in /home/vagrant/www/work/lyf/vendor/neomerx/json-api/src/Factories/Factory.php:173
Stack trace:
#0 /home/vagrant/www/work/lyf/vendor/neomerx/json-api/src/Factories/Factory.php(173): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(4096, 'Argument 6 pass...', '/home/vagrant/w...', 173, Array)
#1 /home/vagrant/www/work/lyf/vendor/neomerx/json-api/src/Parameters/ParametersParser.php(100): Neomerx\JsonApi\Factories\Factory->createParameters(Object(Neomerx\JsonApi\Parameters\Headers\Header), Object(Neomerx\JsonApi\Parameters\Headers\AcceptHeader), NULL, NULL, NULL, '2', NULL, NULL)
#2 /home/vagrant/www/work/lyf/vendor/neomerx/limoncello/src/Http/JsonApiTrait.php(305): Neomerx\JsonApi\Parameters\ParametersParser->parse(Object(Lyf\Http\Controllers\JsonApi\LaravelIntegration), Object(Neomerx\Limoncello\Errors\ExceptionThrower))
#3 /home/vagrant/www/work/lyf/vendor/neomerx/limoncello/src/Http/JsonApiTrait.php(316): Lyf\Http\Controllers\JsonApi\JsonApiController->getUncheckedParameters()
#4 /home/vagrant/www/work/lyf/vendor/neomerx/limoncello/src/Http/JsonApiTrait.php(334): Lyf\Http\Controllers\JsonApi\JsonApiController->checkParameters()
#5 /home/vagrant/www/work/lyf/vendor/neomerx/limoncello/src/Http/JsonApiTrait.php(398): Lyf\Http\Controllers\JsonApi\JsonApiController->getParameters()
#6 /home/vagrant/www/work/lyf/app/Http/Controllers/JsonApi/JsonApiController.php(46): Lyf\Http\Controllers\JsonApi\JsonApiController->getContentResponse(Array, 200, NULL, NULL)
#7 /home/vagrant/www/work/lyf/app/Http/Controllers/Api/UsersController.php(31): Lyf\Http\Controllers\JsonApi\JsonApiController->getResponse(Object(Illuminate\Database\Eloquent\Collection))
#8 [internal function]: Lyf\Http\Controllers\Api\UsersController->index()
```

**Comment by neomerx** [comment]
I've added a branch. However after reading issue I think it might be a [right behaviour](https://github.com/neomerx/json-api/wiki/Parsing-API-Parameters) ([this comment in particular](https://github.com/neomerx/limoncello/blob/master/src/Http/JsonApiTrait.php#L90-L97)). It would be nice if you add even a simple test for this test  case (to the `issue58` branch).

I think you need to override $allowedPagingParameters in your Controller
```php
protected $allowedPagingParameters = [
    'page',
];
```

**Comment by LavaToaster** [comment]
I've updated the issue to add an error log in.

**Comment by neomerx** [comment]
@Lavoaster fixed in `development` branch. Will be released in 0.5.11 (not later than next Friday).

**Comment by neomerx** [comment]
@Lavoaster After thinking a while... How do you think it should work in case of invalid parameters
- silently ignore them
- throw BadRequest?

**Comment by neomerx** [comment]
@Lavoaster I see your `Bad request` suggestion in the first post :smile:
