### ISSUE TITLE
InvalidArgumentException with message 'type'

### ISSUE THREAD

**Issue by nickelozz** [neomerx/json-api#87]
Hello!

I'm trying to implement this package into my laravel 5 app by using it in combination with cloudcreativity/laravel-json-api... however while trying to make a simple get of all users resource I get a 500 http status code and inside my laravel.log I get the following:

```
local.ERROR: exception 'InvalidArgumentException' with message 'type' in /opt/admysis/panel-siscoweb/webserver/vendor/neomerx/json-api/src/Factories/Exceptions.php:37
```

I'm not sure  why this is happening but as far as I've been able to track this down it seems like the data encoding is failing for some reason. Is there any way I can determine what's causing this exception to be thrown? Thanks in advance!!!

The stack trace in case it's of any help:

```
#0 /opt/admysis/panel-siscoweb/webserver/vendor/neomerx/json-api/src/Schema/Container.php(121): Neomerx\JsonApi\Factories\Exceptions::throwInvalidArgument('type', 'PanelSW\\Models\\...')
#1 /opt/admysis/panel-siscoweb/webserver/vendor/neomerx/json-api/src/Schema/Container.php(106): Neomerx\JsonApi\Schema\Container->getSchemaByType('PanelSW\\Models\\...')
#2 /opt/admysis/panel-siscoweb/webserver/vendor/neomerx/json-api/src/Encoder/Parser/Parser.php(234): Neomerx\JsonApi\Schema\Container->getSchema(Object(PanelSW\Models\Usuario))
#3 /opt/admysis/panel-siscoweb/webserver/vendor/neomerx/json-api/src/Encoder/Parser/Parser.php(151): Neomerx\JsonApi\Encoder\Parser\Parser->getSchema(Object(PanelSW\Models\Usuario))
#4 /opt/admysis/panel-siscoweb/webserver/vendor/neomerx/json-api/src/Encoder/Parser/Parser.php(125): Neomerx\JsonApi\Encoder\Parser\Parser::parseData()
#5 /opt/admysis/panel-siscoweb/webserver/vendor/neomerx/json-api/src/Encoder/Encoder.php(233): Neomerx\JsonApi\Encoder\Parser\Parser::parse(Object(PanelSW\Models\Usuario))
#6 /opt/admysis/panel-siscoweb/webserver/vendor/neomerx/json-api/src/Encoder/Encoder.php(157): Neomerx\JsonApi\Encoder\Encoder->encodeDataInternal(Object(Neomerx\JsonApi\Schema\Container), Object(PanelSW\Models\Usuario), Object(Neomerx\JsonApi\Parameters\Parameters))
#7 /opt/admysis/panel-siscoweb/webserver/vendor/cloudcreativity/laravel-json-api/src/Http/Responses/ResponsesHelper.php(107): Neomerx\JsonApi\Encoder\Encoder->encodeData(Object(PanelSW\Models\Usuario), Object(Neomerx\JsonApi\Parameters\Parameters))
#8 /opt/admysis/panel-siscoweb/webserver/app/Http/Controllers/V1/Auth/AuthController.php(36): CloudCreativity\JsonApi\Http\Responses\ResponsesHelper->content(Object(PanelSW\Models\Usuario))
#9 [internal function]: PanelSW\Http\Controllers\V1\Auth\AuthController->signIn()
#10 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(256): call_user_func_array(Array, Array)
#11 /opt/admysis/panel-siscoweb/webserver/vendor/cloudcreativity/laravel-json-api/src/Http/Controllers/JsonApiController.php(54): Illuminate\Routing\Controller->callAction('signin', Array)
#12 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(164): CloudCreativity\JsonApi\Http\Controllers\JsonApiController->callAction('signin', Array)
#13 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(112): Illuminate\Routing\ControllerDispatcher->call(Object(PanelSW\Http\Controllers\V1\Auth\AuthController), Object(Illuminate\Routing\Route), 'signin')
#14 [internal function]: Illuminate\Routing\ControllerDispatcher->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#16 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#17 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#18 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(114): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(69): Illuminate\Routing\ControllerDispatcher->callWithinStack(Object(PanelSW\Http\Controllers\V1\Auth\AuthController), Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'signin')
#20 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Routing/Route.php(201): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request), 'PanelSW\\Http\\Co...', 'signin')
#21 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Routing/Route.php(134): Illuminate\Routing\Route->runWithCustomDispatcher(Object(Illuminate\Http\Request))
#22 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Routing/Router.php(704): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#23 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#24 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 /opt/admysis/panel-siscoweb/webserver/vendor/cloudcreativity/laravel-json-api/src/Http/Middleware/BootJsonApi.php(86): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 [internal function]: CloudCreativity\JsonApi\Http\Middleware\BootJsonApi->handle(Object(Illuminate\Http\Request), Object(Closure), '/api/v1')
#27 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#28 /opt/admysis/panel-siscoweb/webserver/vendor/neomerx/cors-illuminate/src/CorsMiddleware.php(76): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 [internal function]: Neomerx\CorsIlluminate\CorsMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#31 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Routing/Router.php(706): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#34 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Routing/Router.php(671): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#35 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Routing/Router.php(631): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#36 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(236): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#37 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#38 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(139): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#39 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 [internal function]: Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#41 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#42 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 [internal function]: Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#44 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#45 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 [internal function]: Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#47 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#48 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 [internal function]: Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#50 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#51 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 [internal function]: Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#53 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#54 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(42): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#55 [internal function]: Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#56 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(124): call_user_func_array(Array, Array)
#57 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#58 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#59 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(122): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#60 /opt/admysis/panel-siscoweb/webserver/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(87): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#61 /opt/admysis/panel-siscoweb/frontend/index.php(54): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#62 {main}
```

**Comment by neomerx** [comment]
You haven't registered any `Schema` for `PanelSW\Models\Usuario` model.

Please check documentation for `cloudcreativity/laravel-json-api` how it should be done.

I think it should be somewhere [here](https://github.com/cloudcreativity/laravel-json-api/blob/master/config/json-api.php#L35-L44)

**Comment by lindyhopchris** [comment]
@neomerx i think the exception message should be clearer rather than just saying `type` - i.e. it should say that a schema isn't registered.

@nickelozz if you're having any problems with the `cloudcreativity/laravel-json-api` package feel free to create issues on that package and I'll be sure to respond.

**Comment by nickelozz** [comment]
@neomerx thanks for your answer I'm sorry for bothering you with something that's not responsibility of your package... you've pointed me in the right direction!! even tho I did have the corresponding schema registered in my json-api.php file published in my config folder, I was failing to provide the right namespace... for some reason I thought I could simply add it to the top of the configuration file with a "use" line but instead I had to put the entire namespace of each file in the string as follows:

```
C::SCHEMAS => [
        Schemas::DEFAULTS => [
            'PanelSW\Models\Usuario' => 'PanelSW\Schemas\UsuarioSchema',
        ],
        // merged with defaults if JSON API middleware uses the 'extra-schemas' name.
        'extra-schemas' => [
            // 'Person' => 'PersonSchema',
        ],
    ],
```

Once again sorry to bother you @neomerx. I agree with you @lindyhopchris perhaps if the exception was a lil more specific I could've figured it out on my own.

Thanks guys

**Comment by neomerx** [comment]
@nickelozz hint You can use `class` constant in combination with `use` statements

``` php
use PanelSW\Models\Usuario;
use PanelSW\Schemas\UsuarioSchema;

...

C::SCHEMAS => [
        Schemas::DEFAULTS => [
            Usuario::class => UsuarioSchema::class,
        ],
    ],
```

**Comment by neomerx** [comment]
@lindyhopchris 

I'd like to have it with localization. Something like

``` php
Exceptions::throwInvalidArgument('type', $type, T::trans('Schema is not registered for type.'));
```

just haven't figured out how to do it properly

**Comment by nickelozz** [comment]
Excellent! works like a charm ty
